fallback_nodes:
    - 'f('
sequence_nodes:
    - 's('              
condition_nodes:
    - '0 at pos (-0.1, 0.0, 0.0)?'
    - '1 at pos (-0.1, 0.0, 0.0192)?'
    - '0 at pos (0.0, 0.0, 0.0)?'
    - '1 at pos (0.0, 0.0, 0.0)?'
    - '2 at pos (0.0, 0.0, 0.0)?'
    - '0 on 1?'
    - '1 on 0?'

action_nodes:
    - 'pick 0!'
    - 'pick 1!'
    - 'pick 2!'
    - 'put 0 at (0.0, 0.0, 0.0)!'
    - 'put 1 at (0.0, 0.0, 0.0)!'
    - 'put 2 at (0.0, 0.0, 0.0)!'
    - 'put 0 at (-0.1, 0.0, 0.0)!'
    - 'put 1 at (-0.1, 0.0, 0.0)!'
    - 'put 2 at (-0.1, 0.0, 0.0)!'
    - 'put 0 at (0.0, 0.05, 0.0)!'
    - 'put 1 at (0.0, 0.05, 0.0)!'
    - 'put 2 at (0.0, 0.05, 0.0)!'
    - 'put 0 at (0.0, -0.05, 0.0)!'
    - 'put 1 at (0.0, -0.05, 0.0)!'
    - 'put 2 at (0.0, -0.05, 0.0)!'
    - 'put 0 on 1!'
    - 'put 1 on 0!'
    - 'apply force 0!'
    - 'apply force 1!'
    - 'apply force 2!'
    
atomic_fallback_nodes:
up_node:
    - ')'