fallback_nodes:
    - 'f('
sequence_nodes:
    - 's('              
condition_nodes:
    - 'picked 0?'
    - 'picked 1?'
    - 'picked 2?'
    - '0 at pos (0.0, 0.05, 0.0)?'
    - '1 at pos (0.0, 0.05, 0.0192)?'
    - '2 at pos (0.0, 0.05, 0.0384)?'
    - '0 on 1?'
    - '0 on 2?'
    - '1 on 0?'
    - '1 on 2?'
    - '2 on 0?'
    - '2 on 1?'
action_nodes:
    - 'pick 0!'
    - 'pick 1!'
    - 'pick 2!'
    - 'place at (0.0, 0.05, 0.0)!'
    - 'place on 0!'
    - 'place on 1!'
    - 'place on 2!'
    - 'apply force 0!'
    - 'apply force 1!'
    - 'apply force 2!'
atomic_fallback_nodes:
up_node:
    - ')'