fallback_nodes:
    - 'f('
sequence_nodes:
    - 's('              
condition_nodes:
    - 'picked 0?'
    - 'picked 1?'
    - 'picked 2?'
    - 'picked 3?'
    - '0 at pos (0.0, 0.0, 0.0)?'
    - '1 at pos (0.0, 0.0, 0.0192)?'
    - '2 at pos (0.016, -0.032, 0.0)?'
    - '3 at pos (0.016, 0.032, 0.0)?'
    - '0 on 1?'
    - '0 on 2?'
    - '0 on 3?'
    - '1 on 0?'
    - '1 on 2?'
    - '1 on 3?'
    - '2 on 0?'
    - '2 on 1?'
    - '2 on 3?'
    - '3 on 0?'
    - '3 on 1?'
    - '3 on 2?'
    
action_nodes:
    - 'pick 0!'
    - 'pick 1!'
    - 'pick 2!'
    - 'pick 3!'
    - 'place at (0.0, 0.0, 0.0)!'
    - 'place at (0.016, -0.032, 0.0)!'
    - 'place at (0.016, 0.032, 0.0)!'
    - 'place on 0!'
    - 'place on 1!'
    - 'place on 2!'
    - 'place on 3!'
    - 'apply force 0!'
    - 'apply force 1!'
    - 'apply force 2!'
    - 'apply force 3!'
    
atomic_fallback_nodes:
up_node:
    - ')'